### ISSUE TITLE
[Android Bootcamp] Project 3: Grid Image Search

### ISSUE THREAD

**Issue by ginacyliu** [ginacyliu/AndroidBootcamp#4]
My App is complete, please review. @nidhi1608, @codepathreview and @thecodepath

Time spent: 6 hours spent in coding
Completed user stories:
- [x] User can enter a search query that will display a grid of image results from the Google Image API.
- [x] User can click on "settings" which allows selection of advanced search options to filter results
- [x] User can configure advanced search filters such as:
- [x] Size (small, medium, large, extra-large)
- [x] Color filter (black, blue, brown, gray, green, etc...)
- [x] Type (faces, photo, clip art, line art)
- [x] Site (espn.com)
- [x] Subsequent searches will have any filters applied to the search results
- [x] User can tap on any image in results to see the image full-screen
- [x] User can scroll down “infinitely” to continue loading more image results (up to 8 pages)
- [ ] Optional: Use the ActionBar SearchView or custom layout as the query box instead of an EditText
- [ ] Optional: User can share an image to their friends or email it to themselves
- [ ] Optional: Robust error handling, check if internet is available, handle error cases, network failures
- [ ] Optional: Improve the user interface and experiment with image assets and/or styling and coloring
- [ ] Stretch: Replace Filter Settings Activity with a lightweight modal overlay
- [ ] Stretch: User can zoom or pan images displayed in full-screen detail view
- [ ] Stretch: Use the StaggeredGridView to display visually interesting image results

![gridimagesearch](https://cloud.githubusercontent.com/assets/3665964/5164172/3b7598de-740f-11e4-84d1-1ec2ca9e029e.gif)

**Comment by nidhi1608** [comment]
:+1: Looks good overall. I have provided a detailed [Feedback Guide here](https://gist.github.com/nesquena/44091e4727b154d04269) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be very important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
